admin:
  resource: ../src/Controller/Admin
  type: attribute
  prefix: admin/sociallogin/
  name_prefix: sociallogin_admin_

front:
  resource: ../src/Controller/Front
  type: attribute
  prefix: login/
  name_prefix: sociallogin_